<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cd39c9c1-9011-40f8-97e7-0808d3800d90</elementGuidId>
    <imagePath></imagePath>
    <name>select_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product_sort_container"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>